name: "Setup JFrog CLI TOKEN Example"

on: push

permissions:
  contents: read   # ya no usamos id-token

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ vars.JF_URL }}                 # Puedes dejar la variable que ya ten√≠as
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}   # <--- AGREGA ESTE
        with:
          use-jfrog-cli-rc: true                     # necesario cuando usas token

      - name: Run JFrog CLI
        run: |
          jf rt ping
