name: "Setup JFrog CLI with Token"

on: push

permissions:
  contents: read   # Ya no usamos id-token

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ vars.JF_URL }}                 # URL de tu JFrog (variable)
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}   # Token (secreto)

      - name: Run JFrog CLI
        run: |
          jf rt ping
